### ISSUE TITLE
About  costs of memory 

### ISSUE THREAD

**Issue by Synapsess** [NJU-PCALab/AddSR#4]
Hi, thanks for your great work. I would like to know: 1. How much GPU memory is required to train AddSR? 2. During testing, assuming the use of the DrealSR dataset for x4, how much memory is needed? Thank you for your response.

**Comment by Synapsess** [comment]
Sorry to take up your time since this question is just to satisfy my curiosity. 
It seems that GAN/Diffusion-based models are not compared with other Blind-SR methods that use direct supervised training. I wonder the reason for it.

**Comment by CSRuiXie** [comment]
> Hi, thanks for your great work. I would like to know: 1. How much GPU memory is required to train AddSR? 2. During testing, assuming the use of the DrealSR dataset for x4, how much memory is needed? Thank you for your response.
Thank you for your attention to our work! Regarding question 1: Under the default training settings, each device requires approximately 40GB of GPU memory. Regarding question 2: Because the resolution of original LR images in DrealSR dataset are relatively large, we crop them into 128x128 patches for x4 super-resolution. With this setup, approximately 11GB of GPU memory is needed.

**Comment by CSRuiXie** [comment]
Thank you for your attention to our work! Regarding question 1: Under the default training settings, each device requires approximately 40GB of GPU memory. Regarding question 2: Because the resolution of original LR images in DrealSR dataset are relatively large, we crop them into 128x128 patches for x4 super-resolution. With this setup, approximately 11GB of GPU memory is needed.

**Comment by CSRuiXie** [comment]
In my view, Blind-SR methods that utilize direct supervised training tend to produce high-fidelity results that appear blurry, whereas GAN/diffusion-based methods are employed to generate clearer and more realistic results. Since our goal is to generate results with high perception quality, we primarily focus on GAN/diffusion-based methods.

**Comment by Synapsess** [comment]
Thanks for your response. it helps me a lot and has cleared up my confusion. I think this work advances the task of Blind SR.
